export const MODULES = [
  {
    id: 1,
    to: "/app/profile",
    icon: "UserRound",
    name: "Profiles & Networking",
    tagline: "LinkedIn-style, built for science",
    points: [
      "Scientific profile card with field tags",
      "Credential badges & verified status",
      "Citation count and h-index",
      "Follow, connect and endorse peers",
      "AI-suggested collaborators",
    ],
  },
  {
    id: 2,
    to: "/app/papers",
    icon: "FileText",
    name: "Papers & Publishing",
    tagline: "Your research deserves a platform",
    points: [
      "PDF / Word / LaTeX submission",
      "Pre-print publishing with DOI",
      "Version control & co-author credit",
      "Citation generator (APA, MLA, Chicago)",
      "Plagiarism check before submission",
    ],
  },
  {
    id: 3,
    to: "/app/professors",
    icon: "GraduationCap",
    name: "Professors & Mentorship",
    tagline: "Connecting knowledge with curiosity",
    points: [
      "Verified professor profiles",
      "Ask a Professor Q&A",
      "1-on-1 and group mentorship",
      "Research review & thesis guidance",
      "Mentor matching algorithm",
    ],
  },
  {
    id: 4,
    to: "/app/community",
    icon: "MessagesSquare",
    name: "Community & Social",
    tagline: "Because science is collaborative",
    points: [
      "Research posts, articles, lab updates",
      "Scientific reactions beyond likes",
      "Hypothesis board & research threads",
      "Field, university and regional groups",
      "Polls, surveys and challenges",
    ],
  },
  {
    id: 5,
    to: "/app/simulations",
    icon: "Atom",
    name: "Simulation & Visualization",
    tagline: "Bringing research to life digitally",
    points: [
      "Physics, chemistry and biology simulators",
      "Statistical analysis engine",
      "Graph & chart builder",
      "Dataset upload, cleaning, correlations",
      "Shared real-time simulation workspaces",
    ],
  },
  {
    id: 6,
    to: "/app/learn",
    icon: "BookOpen",
    name: "Learning Hub",
    tagline: "For researchers who want to grow",
    points: [
      "Methodology & scientific writing courses",
      "Lab technique video library",
      "Programming for researchers",
      "Quizzes, flashcards and case studies",
      "Certification programs",
    ],
  },
  {
    id: 7,
    to: "/app/projects",
    icon: "FolderKanban",
    name: "Collaboration & Projects",
    tagline: "Research is a team sport",
    points: [
      "Project workspaces and task boards",
      "Milestones and progress reports",
      "Collaborative documents & data sharing",
      "Collaboration board for open projects",
      "Messaging, group chat and video calls",
    ],
  },
  {
    id: 8,
    to: "/app/review",
    icon: "ShieldCheck",
    name: "Peer Review System",
    tagline: "Quality science needs quality review",
    points: [
      "Open and blind review options",
      "Automatic reviewer matching",
      "Structured, scored review forms",
      "Reviewer reputation scores",
      "Community Reviewed badge",
    ],
  },
  {
    id: 9,
    to: "/app/recognition",
    icon: "Trophy",
    name: "Recognition & Gamification",
    tagline: "Motivating the next generation",
    points: [
      "Research Points for contributions",
      "Badges, medals and research ranks",
      "Field leaderboards & spotlights",
      "Verified research record",
      "Grant-ready portfolio export",
    ],
  },
  {
    id: 10,
    to: "/app/events",
    icon: "CalendarDays",
    name: "Events & Conferences",
    tagline: "Connecting the scientific world",
    points: [
      "Virtual conferences and webinars",
      "Science hackathons & symposiums",
      "Journal clubs and workshops",
      "Virtual poster sessions",
      "Local meetups and event recaps",
    ],
  },
  {
    id: 11,
    to: "/app/funding",
    icon: "Banknote",
    name: "Funding & Grants",
    tagline: "Great research needs resources",
    points: [
      "Global grant database & alerts",
      "Grant application helper",
      "Crowdfunding for research",
      "Sponsor matching",
      "Budget planning tool",
    ],
  },
  {
    id: 12,
    to: "/app/assistant",
    icon: "Sparkles",
    name: "AI Research Assistant",
    tagline: "Your 24/7 scientific companion",
    points: [
      "Topic generator & gap identifier",
      "Literature search and citation finder",
      "Writing and methodology advisor",
      "Statistical test recommendations",
      "Paper summaries & pre-review feedback",
    ],
  },
] as const;
