/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSimulationsRouteImport } from './routes/app.simulations'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppRecognitionRouteImport } from './routes/app.recognition'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProfessorsRouteImport } from './routes/app.professors'
import { Route as AppPapersRouteImport } from './routes/app.papers'
import { Route as AppNetworkRouteImport } from './routes/app.network'
import { Route as AppLearnRouteImport } from './routes/app.learn'
import { Route as AppFundingRouteImport } from './routes/app.funding'
import { Route as AppFeedRouteImport } from './routes/app.feed'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulationsRoute = AppSimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppRecognitionRoute = AppRecognitionRouteImport.update({
  id: '/recognition',
  path: '/recognition',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessorsRoute = AppProfessorsRouteImport.update({
  id: '/professors',
  path: '/professors',
  getParentRoute: () => AppRoute,
} as any)
const AppPapersRoute = AppPapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppFundingRoute = AppFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/events': typeof AppEventsRoute
  '/app/feed': typeof AppFeedRoute
  '/app/funding': typeof AppFundingRoute
  '/app/learn': typeof AppLearnRoute
  '/app/network': typeof AppNetworkRoute
  '/app/papers': typeof AppPapersRoute
  '/app/professors': typeof AppProfessorsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/recognition': typeof AppRecognitionRoute
  '/app/review': typeof AppReviewRoute
  '/app/simulations': typeof AppSimulationsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/events': typeof AppEventsRoute
  '/app/feed': typeof AppFeedRoute
  '/app/funding': typeof AppFundingRoute
  '/app/learn': typeof AppLearnRoute
  '/app/network': typeof AppNetworkRoute
  '/app/papers': typeof AppPapersRoute
  '/app/professors': typeof AppProfessorsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/recognition': typeof AppRecognitionRoute
  '/app/review': typeof AppReviewRoute
  '/app/simulations': typeof AppSimulationsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/events': typeof AppEventsRoute
  '/app/feed': typeof AppFeedRoute
  '/app/funding': typeof AppFundingRoute
  '/app/learn': typeof AppLearnRoute
  '/app/network': typeof AppNetworkRoute
  '/app/papers': typeof AppPapersRoute
  '/app/professors': typeof AppProfessorsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/recognition': typeof AppRecognitionRoute
  '/app/review': typeof AppReviewRoute
  '/app/simulations': typeof AppSimulationsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/assistant'
    | '/app/community'
    | '/app/events'
    | '/app/feed'
    | '/app/funding'
    | '/app/learn'
    | '/app/network'
    | '/app/papers'
    | '/app/professors'
    | '/app/profile'
    | '/app/projects'
    | '/app/recognition'
    | '/app/review'
    | '/app/simulations'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/assistant'
    | '/app/community'
    | '/app/events'
    | '/app/feed'
    | '/app/funding'
    | '/app/learn'
    | '/app/network'
    | '/app/papers'
    | '/app/professors'
    | '/app/profile'
    | '/app/projects'
    | '/app/recognition'
    | '/app/review'
    | '/app/simulations'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/assistant'
    | '/app/community'
    | '/app/events'
    | '/app/feed'
    | '/app/funding'
    | '/app/learn'
    | '/app/network'
    | '/app/papers'
    | '/app/professors'
    | '/app/profile'
    | '/app/projects'
    | '/app/recognition'
    | '/app/review'
    | '/app/simulations'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulations': {
      id: '/app/simulations'
      path: '/simulations'
      fullPath: '/app/simulations'
      preLoaderRoute: typeof AppSimulationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recognition': {
      id: '/app/recognition'
      path: '/recognition'
      fullPath: '/app/recognition'
      preLoaderRoute: typeof AppRecognitionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professors': {
      id: '/app/professors'
      path: '/professors'
      fullPath: '/app/professors'
      preLoaderRoute: typeof AppProfessorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/papers': {
      id: '/app/papers'
      path: '/papers'
      fullPath: '/app/papers'
      preLoaderRoute: typeof AppPapersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/network': {
      id: '/app/network'
      path: '/network'
      fullPath: '/app/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn': {
      id: '/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/funding': {
      id: '/app/funding'
      path: '/funding'
      fullPath: '/app/funding'
      preLoaderRoute: typeof AppFundingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppEventsRoute: typeof AppEventsRoute
  AppFeedRoute: typeof AppFeedRoute
  AppFundingRoute: typeof AppFundingRoute
  AppLearnRoute: typeof AppLearnRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppPapersRoute: typeof AppPapersRoute
  AppProfessorsRoute: typeof AppProfessorsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppRecognitionRoute: typeof AppRecognitionRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSimulationsRoute: typeof AppSimulationsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppEventsRoute: AppEventsRoute,
  AppFeedRoute: AppFeedRoute,
  AppFundingRoute: AppFundingRoute,
  AppLearnRoute: AppLearnRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppPapersRoute: AppPapersRoute,
  AppProfessorsRoute: AppProfessorsRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppRecognitionRoute: AppRecognitionRoute,
  AppReviewRoute: AppReviewRoute,
  AppSimulationsRoute: AppSimulationsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
